package Chat;


/**
* Chat/CannotEstablishConnection.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Chat.idl
* Wednesday, April 13, 2016 6:17:13 PM EDT
*/

public final class CannotEstablishConnection extends org.omg.CORBA.UserException
{

  public CannotEstablishConnection ()
  {
    super(CannotEstablishConnectionHelper.id());
  } // ctor


  public CannotEstablishConnection (String $reason)
  {
    super(CannotEstablishConnectionHelper.id() + "  " + $reason);
  } // ctor

} // class CannotEstablishConnection
