package Chat;

/**
* Chat/CannotEstablishConnectionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Chat.idl
* Wednesday, April 13, 2016 6:17:13 PM EDT
*/

public final class CannotEstablishConnectionHolder implements org.omg.CORBA.portable.Streamable
{
  public Chat.CannotEstablishConnection value = null;

  public CannotEstablishConnectionHolder ()
  {
  }

  public CannotEstablishConnectionHolder (Chat.CannotEstablishConnection initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Chat.CannotEstablishConnectionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Chat.CannotEstablishConnectionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Chat.CannotEstablishConnectionHelper.type ();
  }

}
