package Chat;


/**
* Chat/ChatServerSvcs.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Chat.idl
* Wednesday, April 13, 2016 6:17:13 PM EDT
*/

public interface ChatServerSvcs extends ChatServerSvcsOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface ChatServerSvcs
