package Chat;


/**
* Chat/ChatClientSvcsPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Chat.idl
* Wednesday, April 13, 2016 6:17:13 PM EDT
*/

public abstract class ChatClientSvcsPOA extends org.omg.PortableServer.Servant
 implements Chat.ChatClientSvcsOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("receiveMsg", new java.lang.Integer (0));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // Chat/ChatClientSvcs/receiveMsg
       {
         int t[] = Chat.TimeVectorHelper.read (in);
         int senderId = in.read_long ();
         String msg = in.read_string ();
         this.receiveMsg (t, senderId, msg);
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:Chat/ChatClientSvcs:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public ChatClientSvcs _this() 
  {
    return ChatClientSvcsHelper.narrow(
    super._this_object());
  }

  public ChatClientSvcs _this(org.omg.CORBA.ORB orb) 
  {
    return ChatClientSvcsHelper.narrow(
    super._this_object(orb));
  }


} // class ChatClientSvcsPOA
