package Chat;

/**
* Chat/ChatClientSvcsHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Chat.idl
* Wednesday, April 13, 2016 6:17:13 PM EDT
*/

public final class ChatClientSvcsHolder implements org.omg.CORBA.portable.Streamable
{
  public Chat.ChatClientSvcs value = null;

  public ChatClientSvcsHolder ()
  {
  }

  public ChatClientSvcsHolder (Chat.ChatClientSvcs initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Chat.ChatClientSvcsHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Chat.ChatClientSvcsHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Chat.ChatClientSvcsHelper.type ();
  }

}
