package Chat;


/**
* Chat/ChatClientSvcsOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Chat.idl
* Wednesday, April 13, 2016 6:17:13 PM EDT
*/

public interface ChatClientSvcsOperations 
{
  void receiveMsg (int[] t, int senderId, String msg);
} // interface ChatClientSvcsOperations
