package Chat;


/**
* Chat/DuplicateClient.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Chat.idl
* Wednesday, April 13, 2016 6:17:13 PM EDT
*/

public final class DuplicateClient extends org.omg.CORBA.UserException
{

  public DuplicateClient ()
  {
    super(DuplicateClientHelper.id());
  } // ctor


  public DuplicateClient (String $reason)
  {
    super(DuplicateClientHelper.id() + "  " + $reason);
  } // ctor

} // class DuplicateClient
