package Chat;

/**
* Chat/DuplicateClientHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Chat.idl
* Wednesday, April 13, 2016 6:17:13 PM EDT
*/

public final class DuplicateClientHolder implements org.omg.CORBA.portable.Streamable
{
  public Chat.DuplicateClient value = null;

  public DuplicateClientHolder ()
  {
  }

  public DuplicateClientHolder (Chat.DuplicateClient initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Chat.DuplicateClientHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Chat.DuplicateClientHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Chat.DuplicateClientHelper.type ();
  }

}
