package Chat;


/**
* Chat/MAX_NUM_PROCESSES.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Chat.idl
* Wednesday, April 13, 2016 6:17:13 PM EDT
*/

public interface MAX_NUM_PROCESSES
{
  public static final int value = (int)(10);
}
