package Chat;

/**
* Chat/UnknownClientHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Chat.idl
* Wednesday, April 13, 2016 6:17:13 PM EDT
*/

public final class UnknownClientHolder implements org.omg.CORBA.portable.Streamable
{
  public Chat.UnknownClient value = null;

  public UnknownClientHolder ()
  {
  }

  public UnknownClientHolder (Chat.UnknownClient initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Chat.UnknownClientHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Chat.UnknownClientHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Chat.UnknownClientHelper.type ();
  }

}
