package Chat;


/**
* Chat/UnknownClient.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Chat.idl
* Wednesday, April 13, 2016 6:17:13 PM EDT
*/

public final class UnknownClient extends org.omg.CORBA.UserException
{

  public UnknownClient ()
  {
    super(UnknownClientHelper.id());
  } // ctor


  public UnknownClient (String $reason)
  {
    super(UnknownClientHelper.id() + "  " + $reason);
  } // ctor

} // class UnknownClient
